server:
  port: 8888

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/binance?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 3
      minimum-idle: 1
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.binance.demo.entity

binance:
  isUseTest: true
  proxy:
    enable: true
    ip: 127.0.0.1
    port: 2022
    username:
    password:
  test:
    API-KEY: 123
    SECRET: 123

## nacos注册中心配置
#spring:
#  cloud:
#    nacos:
#      discovery:
#        namespace: 5bc37a7e-eafd-4539-8180-3811cd31fd1c
#        server-addr: http://nacos-live-stage.eyolo.net:80
#        service: ${spring.application.name}

# Tomcat
#server:
#  tomcat:
#    uri-encoding: UTF-8
#    #最小线程数
#    min-spare-threads: 500
#    #最大线程数
#    max-threads: 2500
#    #最大链接数
#    max-connections: 6500
#    #最大等待队列长度
#    accept-count: 1000
#    #请求头最大长度kb
#    max-http-header-size: 1048576
#    #请请求体最大长度kb
#    #max-http-post-size: 2097152
#  #服务http端口
#  #port: 8080
#  #链接建立超时时间
#  connection-timeout: 12000
